"use client";

import React from 'react';
import { Shield, Lock, Eye, Database, UserCheck, Smartphone, Globe, FileText, Server, Trash2, AlertCircle } from 'lucide-react';
import Link from 'next/link';

const DopplerVPNPrivacyPolicy = () => {
  const sections = [
    {
      icon: Database,
      title: "Information We Collect",
      content: [
        "Device Identifier: A unique identifier for your device, used solely to enforce device limits and designate your primary device",
        "Subscription Status: Information about your subscription status, managed through RevenueCat and Apple",
        "App Usage Metadata: Basic app functionality data (e.g., connection status) required for service operation",
        "We do NOT collect your email address",
        "We do NOT collect your name or personal identity information",
        "We do NOT collect your browsing history or websites visited",
        "We do NOT collect your IP address logs or connection timestamps",
        "We do NOT collect bandwidth usage or data transfer logs",
        "We do NOT collect DNS queries or traffic content"
      ]
    },
    {
      icon: Eye,
      title: "How We Use Your Information",
      content: [
        "Device limits: To enforce the maximum of 10 devices per subscription",
        "Primary device: To designate one device as your primary device for account management",
        "Abuse prevention: To detect and prevent subscription sharing abuse",
        "Service delivery: To provide and maintain the VPN service",
        "We do NOT use your information for advertising or marketing purposes",
        "We do NOT sell, rent, or trade your information to third parties",
        "We do NOT build user profiles or track your online behavior"
      ]
    },
    {
      icon: Lock,
      title: "Our No-Logs Policy",
      content: [
        "We maintain a strict no-logs policy for VPN usage",
        "We do NOT log which websites or services you access through the VPN",
        "We do NOT log your connection timestamps (when you connect or disconnect)",
        "We do NOT log your original IP address or assigned VPN IP address",
        "We do NOT log your bandwidth consumption or data transfer amounts",
        "We do NOT log your DNS queries or browsing history",
        "We do NOT monitor, record, or store the content of your internet traffic",
        "Our infrastructure is designed to minimize data collection while providing reliable service"
      ]
    },
    {
      icon: Smartphone,
      title: "Device Identifier Details",
      content: [
        "Purpose: Device identifiers are collected solely to manage your 10-device limit and primary device designation",
        "What it is: A unique identifier generated by your device's operating system (not your IMEI, phone number, or Apple ID)",
        "Storage: Device identifiers are stored securely on our servers with appropriate encryption",
        "Retention: Device identifiers are retained for the duration of your subscription plus 30 days after cancellation",
        "Deletion: Upon request, we will delete your device identifiers from our systems within 30 days",
        "We cannot and do not use device identifiers to track your location, browsing activity, or personal identity"
      ]
    },
    {
      icon: Server,
      title: "Third-Party Services",
      content: [
        "Apple App Store: Handles all payment processing, billing, and subscription management. Apple's privacy policy applies to payment data",
        "RevenueCat: Manages subscription status between Apple and our service. RevenueCat receives anonymized subscription data only",
        "We do NOT share device identifiers with Apple, RevenueCat, or any other third party",
        "We do NOT use advertising SDKs, analytics trackers, or social media pixels in Doppler VPN",
        "We do NOT integrate with Meta (Facebook), Google Analytics, or similar tracking services within the VPN app",
        "Our VPN servers do not share your traffic data with any third parties"
      ]
    },
    {
      icon: UserCheck,
      title: "Your Rights",
      content: [
        "Access: Request information about what data we hold about you",
        "Deletion: Request deletion of your device identifier data at any time",
        "Portability: Request a copy of your data in a machine-readable format",
        "Correction: Request correction of any inaccurate data (limited applicability given minimal data collection)",
        "Objection: Object to processing of your data for specific purposes",
        "Withdrawal: Withdraw consent for data processing at any time (may affect service functionality)",
        "To exercise any of these rights, contact us at support@simnetiq.store"
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-white py-24">
      {/* Header Section */}
      <section className="bg-white">
        <div className="mx-auto max-w-2xl px-6 lg:max-w-7xl lg:px-8">
          <div className="text-center">
            <h2 className="text-center text-xl font-semibold text-tufts-blue">
              <span>{'{ '}</span>
              Privacy & Security
              <span>{' }'}</span>
            </h2>
            <p className="mx-auto mt-12 max-w-4xl text-center text-4xl font-semibold tracking-tight text-eerie-black sm:text-5xl">
              Doppler VPN Privacy Policy
            </p>
            <p className="mx-auto mt-6 max-w-2xl text-center text-lg text-cool-black">
              Learn how Doppler VPN protects your privacy. We collect minimal data and maintain
              a strict no-logs policy for your VPN activity.
            </p>
            <div className="flex items-center justify-center mt-8">
              <Shield className="w-8 h-8 text-tufts-blue mr-2" />
              <p className="text-sm text-cool-black">
                Effective Date: December 30, 2025 | Last Updated: December 30, 2025
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Content Section */}
      <section className="bg-white">
        <div className="mx-auto max-w-2xl px-6 lg:max-w-7xl lg:px-8 mt-6">

          {/* Introduction */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <h2 className="text-2xl font-medium tracking-tight text-eerie-black mb-4">Privacy Commitment</h2>
                <p className="text-cool-black leading-relaxed mb-4">
                  At Simnetiq Ltd, we built Doppler VPN with privacy as a core principle. This Privacy Policy
                  explains our minimal data collection practices and our commitment to protecting your privacy
                  while using our VPN service.
                </p>
                <p className="text-cool-black leading-relaxed mb-4">
                  Doppler VPN is part of the Simnetiq product ecosystem. This VPN-specific Privacy Policy
                  supplements the main Simnetiq Privacy Policy. For general company privacy practices, please
                  refer to our main Privacy Policy.
                </p>
                <p className="text-cool-black leading-relaxed mb-4">
                  <strong>Our core privacy principles:</strong> We collect only what is absolutely necessary
                  to provide the service. We do not log your VPN activity. We do not sell your data.
                </p>
                <div className="bg-green-50 border-l-4 border-green-400 p-4 rounded-lg mt-4">
                  <p className="text-green-800 text-sm">
                    <strong>Minimal Data Collection:</strong> We only collect a device identifier to manage your
                    10-device limit. We do NOT collect emails, names, browsing history, IP logs, or any VPN usage data.
                  </p>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

          {/* Data Collection Summary */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <h2 className="text-2xl font-medium tracking-tight text-eerie-black mb-4">Data Collection Summary</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="bg-green-50 p-6 rounded-lg">
                    <h3 className="text-lg font-semibold text-green-800 mb-4 flex items-center">
                      <Lock className="w-5 h-5 mr-2" />
                      What We Collect
                    </h3>
                    <ul className="space-y-2 text-green-700">
                      <li className="flex items-start">
                        <span className="text-green-600 mr-2">✓</span>
                        Device identifier (for device limit enforcement)
                      </li>
                      <li className="flex items-start">
                        <span className="text-green-600 mr-2">✓</span>
                        Subscription status (via RevenueCat/Apple)
                      </li>
                    </ul>
                  </div>
                  <div className="bg-red-50 p-6 rounded-lg">
                    <h3 className="text-lg font-semibold text-red-800 mb-4 flex items-center">
                      <Shield className="w-5 h-5 mr-2" />
                      What We Do NOT Collect
                    </h3>
                    <ul className="space-y-2 text-red-700">
                      <li className="flex items-start">
                        <span className="text-red-600 mr-2">✗</span>
                        Email addresses or names
                      </li>
                      <li className="flex items-start">
                        <span className="text-red-600 mr-2">✗</span>
                        Browsing history or websites visited
                      </li>
                      <li className="flex items-start">
                        <span className="text-red-600 mr-2">✗</span>
                        IP address logs or timestamps
                      </li>
                      <li className="flex items-start">
                        <span className="text-red-600 mr-2">✗</span>
                        Bandwidth usage or traffic content
                      </li>
                      <li className="flex items-start">
                        <span className="text-red-600 mr-2">✗</span>
                        DNS queries or connection logs
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

          {/* Main Sections */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
            {sections.map((section, index) => {
              const IconComponent = section.icon;
              return (
                <div
                  key={index}
                  className="relative"
                >
                  <div className="absolute inset-px rounded-xl bg-white"></div>
                  <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
                    <div className="px-8 pt-8 pb-8">
                      <div className="flex items-center mb-6">
                        <div className="w-12 h-12 bg-tufts-blue/10 rounded-xl flex items-center justify-center mr-4">
                          <IconComponent className="w-6 h-6 text-tufts-blue" />
                        </div>
                        <h2 className="text-xl font-medium tracking-tight text-eerie-black">{section.title}</h2>
                      </div>
                      <ul className="space-y-3">
                        {section.content.map((item, itemIndex) => (
                          <li key={itemIndex} className="flex items-start">
                            <div className="w-2 h-2 bg-tufts-blue rounded-full mt-2 mr-3 flex-shrink-0"></div>
                            <span className="text-cool-black leading-relaxed">{item}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                  <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
                </div>
              );
            })}
          </div>

          {/* Data Retention */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <div className="flex items-center mb-4">
                  <Trash2 className="w-8 h-8 text-tufts-blue mr-3" />
                  <h2 className="text-2xl font-medium tracking-tight text-eerie-black">Data Retention</h2>
                </div>
                <div className="space-y-4 text-cool-black">
                  <p>
                    We retain data only for as long as necessary to provide the service:
                  </p>
                  <ul className="space-y-3 ml-4">
                    <li>
                      <strong>Device Identifiers:</strong> Retained for the duration of your active subscription,
                      plus 30 days after cancellation to allow for subscription restoration
                    </li>
                    <li>
                      <strong>Subscription Status:</strong> Managed by Apple/RevenueCat; we store only current status
                    </li>
                    <li>
                      <strong>VPN Activity:</strong> Not retained - we do not log VPN usage
                    </li>
                  </ul>
                  <p>
                    You may request deletion of your device identifier data at any time by contacting
                    support@simnetiq.store. We will process deletion requests within 30 days.
                  </p>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

          {/* Data Security */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <div className="flex items-center mb-4">
                  <Lock className="w-8 h-8 text-tufts-blue mr-3" />
                  <h2 className="text-2xl font-medium tracking-tight text-eerie-black">Data Security</h2>
                </div>
                <div className="space-y-4 text-cool-black">
                  <p>
                    We implement appropriate technical and organizational measures to protect the limited data we collect:
                  </p>
                  <ul className="space-y-2 ml-4">
                    <li>• Encryption of device identifiers at rest and in transit</li>
                    <li>• Secure server infrastructure with access controls</li>
                    <li>• Regular security assessments and updates</li>
                    <li>• Minimal data collection reduces exposure risk</li>
                  </ul>
                  <p>
                    Your VPN traffic is encrypted using industry-standard protocols. We do not inspect,
                    log, or store the content of your encrypted traffic.
                  </p>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

          {/* International Data Transfers */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <div className="flex items-center mb-4">
                  <Globe className="w-8 h-8 text-tufts-blue mr-3" />
                  <h2 className="text-2xl font-medium tracking-tight text-eerie-black">International Data Transfers</h2>
                </div>
                <div className="space-y-4 text-cool-black">
                  <p>
                    Simnetiq Ltd is based in the United Kingdom. Your device identifier data may be processed
                    on servers located in various jurisdictions.
                  </p>
                  <p>
                    When data is transferred outside the UK/EEA, we ensure appropriate safeguards are in place:
                  </p>
                  <ul className="space-y-2 ml-4">
                    <li>• Standard Contractual Clauses (SCCs) approved by relevant authorities</li>
                    <li>• Data Privacy Framework certification where applicable</li>
                    <li>• Adequacy decisions for transfers to countries with equivalent protection</li>
                  </ul>
                  <p>
                    Apple and RevenueCat may process subscription data in accordance with their respective
                    privacy policies and international data transfer mechanisms.
                  </p>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

          {/* Children's Privacy */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <h2 className="text-2xl font-medium tracking-tight text-eerie-black mb-4">Children&apos;s Privacy</h2>
                <div className="space-y-3 text-cool-black">
                  <p>
                    Doppler VPN is not intended for children under 13 years of age. We do not knowingly
                    collect data from children under 13.
                  </p>
                  <p>
                    If you are a parent or guardian and believe your child has used Doppler VPN, please
                    contact us. Since we do not collect personal information like email or name, there
                    is minimal data to remove, but we will assist with device identifier deletion upon request.
                  </p>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

          {/* Legal Basis (GDPR) */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <h2 className="text-2xl font-medium tracking-tight text-eerie-black mb-4">Legal Basis for Processing (GDPR)</h2>
                <div className="space-y-4 text-cool-black">
                  <div>
                    <h3 className="font-semibold mb-2">Contract Performance (Art. 6(1)(b))</h3>
                    <p>
                      We process device identifiers to fulfill our contract with you - specifically to enforce
                      the 10-device limit that is part of your subscription agreement.
                    </p>
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2">Legitimate Interests (Art. 6(1)(f))</h3>
                    <p>
                      We have a legitimate interest in preventing subscription abuse and ensuring fair use
                      of our services, balanced against your privacy rights.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

          {/* Changes to Privacy Policy */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <h2 className="text-2xl font-medium tracking-tight text-eerie-black mb-4">Changes to This Privacy Policy</h2>
                <div className="space-y-3 text-cool-black">
                  <p>
                    We may update this Privacy Policy from time to time. If we make material changes that
                    expand our data collection or use practices, we will notify you through:
                  </p>
                  <ul className="space-y-2 ml-4">
                    <li>• An in-app notification</li>
                    <li>• Updating the &quot;Last Updated&quot; date at the top of this policy</li>
                    <li>• App Store update notes where appropriate</li>
                  </ul>
                  <p>
                    Your continued use of Doppler VPN after changes become effective constitutes acceptance
                    of the updated policy.
                  </p>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

          {/* Contact Information */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <h2 className="text-2xl font-medium tracking-tight text-eerie-black mb-4">Contact Us</h2>
                <div className="space-y-4 text-cool-black">
                  <p>
                    If you have any questions about this Privacy Policy or wish to exercise your data rights,
                    please contact us:
                  </p>
                  <div className="bg-gray-50 p-6 rounded-lg">
                    <div className="space-y-3">
                      <div>
                        <strong>Data Controller:</strong> Simnetiq Ltd<br />
                        <strong>Address:</strong> 2 Frederick Street, Kings Cross<br />
                                London<br />
                                WC1X 0ND<br />
                                United Kingdom <br />
                        <strong>Email:</strong> support@simnetiq.store<br />
                        <strong>Subject Line for Privacy Requests:</strong> &quot;Doppler VPN Privacy Request&quot;
                      </div>
                      <div className="pt-2">
                        <strong>Response Time:</strong> We aim to respond to all privacy inquiries within 30 days
                      </div>
                    </div>
                  </div>
                  <div className="bg-blue-50 border-l-4 border-blue-400 p-4 rounded-lg mt-4">
                    <p className="text-blue-800 text-sm">
                      <strong>Supervisory Authority:</strong> If you are located in the UK and wish to file a complaint,
                      you can contact the Information Commissioner&apos;s Office (ICO) at{' '}
                      <a href="https://ico.org.uk" target="_blank" rel="noopener noreferrer" className="underline">ico.org.uk</a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

          {/* Related Documents */}
          <div className="relative mb-8">
            <div className="absolute inset-px rounded-xl bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-xl">
              <div className="px-8 pt-8 pb-8">
                <h2 className="text-2xl font-medium tracking-tight text-eerie-black mb-4">Related Legal Documents</h2>
                <div className="space-y-4 text-cool-black">
                  <p>
                    This Privacy Policy should be read in conjunction with our other legal documents:
                  </p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-6">
                    <Link
                      href="/doppler-vpn-terms-of-service"
                      className="flex items-center space-x-3 px-4 py-3 bg-tufts-blue text-white rounded-lg hover:bg-blue-700 transition-colors"
                    >
                      <FileText className="w-5 h-5" />
                      <span>VPN Terms of Service</span>
                    </Link>
                    <Link
                      href="/terms-of-service"
                      className="flex items-center space-x-3 px-4 py-3 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors"
                    >
                      <FileText className="w-5 h-5" />
                      <span>Simnetiq Terms</span>
                    </Link>
                    <Link
                      href="/privacy-policy"
                      className="flex items-center space-x-3 px-4 py-3 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors"
                    >
                      <Shield className="w-5 h-5" />
                      <span>Simnetiq Privacy</span>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-xl shadow-sm ring-1 ring-black/5"></div>
          </div>

        </div>
      </section>
    </div>
  );
};

export default DopplerVPNPrivacyPolicy;
